# Generated by Django 6.0.6 on 2026-06-24 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('maintenance', 'Maintenance'), ('idle', 'Idle')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('scheduled_start', models.DateTimeField()),
                ('estimated_completion', models.DateTimeField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='chat.factoryline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='chat.product')),
            ],
            options={
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('units_sold', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='chat.product')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('product', 'month')},
            },
        ),
    ]
