# Generated by Django 6.0.6 on 2026-06-24 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_factoryline_product_productionorder_salesrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.PositiveIntegerField()),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('reorder_point', models.PositiveIntegerField()),
                ('warehouse', models.CharField(default='Main Warehouse', max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='chat.product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
    ]
