# Generated by Django 6.0.6 on 2026-06-24 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_salesforecast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='line',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='salesforecast',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='salesforecast',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='salesrecord',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.CharField(default='Main Warehouse', max_length=100),
        ),
        migrations.CreateModel(
            name='InventoryMonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('actual_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('plan_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_monthly_data', to='chat.product')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('product', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ProductionMonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('actual_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('plan_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_monthly_data', to='chat.product')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('product', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SalesMonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('actual_units', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('plan_units', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_monthly_data', to='chat.product')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('product', 'month')},
            },
        ),
        migrations.DeleteModel(
            name='InventoryRecord',
        ),
        migrations.DeleteModel(
            name='ProductionOrder',
        ),
        migrations.DeleteModel(
            name='SalesForecast',
        ),
        migrations.DeleteModel(
            name='SalesRecord',
        ),
    ]
