# Generated by Django 5.2.1 on 2026-06-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_monthly_actual_plan_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="thinking",
            field=models.TextField(blank=True, default=""),
        ),
    ]
